K_PERCENT_VBUS = 0
K_POSITION = 3
K_SPEED = 2
K_CURRENT = 1
K_VOLTAGE = 4
K_FOLLOWER = 5
K_MOTION_PROFILE = 6
K_MOTION_MAGIC = 7

ALL_MODES = [K_PERCENT_VBUS, K_CURRENT, K_SPEED, K_POSITION, K_VOLTAGE, K_FOLLOWER, K_MOTION_PROFILE, K_MOTION_MAGIC]